# mymaster を 2 台以上の Sentinel が down と判断したらフェイルオーバー
sentinel monitor mymaster redis-master 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
# Docker のコンテナ名でマスターを解決する
sentinel resolve-hostnames yes
